### ISSUE TITLE
feature request：merge Oracle_VM_VirtualBox_Extension_Pack in your best appimage

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/VirtualBox-appimage#3]
i find usb driver not detect cause that were not have
```
 [Oracle_VM_VirtualBox_Extension_Pack-7.0.20-163906.vbox-extpack](https://mirrors.tuna.tsinghua.edu.cn/virtualbox/7.0.20/Oracle_VM_VirtualBox_Extension_Pack-7.0.20-163906.vbox-extpack)	17.4 MiB	2024-07-11 01:51
[Oracle_VM_VirtualBox_Extension_Pack-7.0.20.vbox-extpack](https://mirrors.tuna.tsinghua.edu.cn/virtualbox/7.0.20/Oracle_VM_VirtualBox_Extension_Pack-7.0.20.vbox-extpack)
```

for your appimage

https://mirrors.tuna.tsinghua.edu.cn/virtualbox/7.0.20/

**Comment by ivan-hc** [comment]
Have you downloaded and tested them?

You should download the .vbox-extpack file and open it with VirtualBox, click on "I Agree" and then install them.

This does not seems to work for me.

Don't forget that this is a Conty environment, I'm not sure on how to made the container use usb devices.

Do you know how to do so? Have you tested it on this Appimage? Have it worked?

**Comment by ivan-hc** [comment]
And more important thing, have you followed the instructions at https://github.com/cyberus-technology/virtualbox-kvm?tab=readme-ov-file#usb-pass-through?

This is linked on my README, I said it three times.

**Comment by ivan-hc** [comment]
And this is VirtualBox 7.0.18 "KVM", its a different thing. We can't create a VirtualBox release without KVM patches from https://github.com/cyberus-technology/virtualbox-kvm , normal VirtualBox need modules installed in the kernel to work. This is not what this development build needs. And being it still under development, you should follow instructions on their repo to solve issues yourself.

**Comment by ivan-hc** [comment]
It would be useful if you fork this repo and do your changes by following instructions from https://github.com/Kron4ek/Conty, you can also build the AppImage yourself using github actions, from your fork, and test your improvements.

If you can, try to help fix issues this way, do not open issues of things that cannot be fixed right now.

I've been trying to create AppImage packages for GNOME Boxes for a year, without success, and I had totally given up on building VirtualBox, because it was impossible.

But I've been studying Conty for three days, and I discovered VirtualBox KVM only 15 hours ago (and in the meantime I went to sleep and did other things during the day), I don't even know how I managed to build a VirtualBox AppImage.

It's just a matter of testing and research, so if you're interested in improving a specific feature, you better study it carefully, so that I can study a little more how Conty works and how to improve other projects I have.

-----------------------------------
OFF TOPIC

PS: @newyorkthink  I recognize that it is thanks to you that I experimented and discovered how to use the system language, and I applied this in all other projects. Thank you.

But if you're hoping to use this version in languages ​​other than English, that's not possible for now. The VirtualBox KVM package is in English only. So, before you also ask me to support other languages, know that for now it is not possible, there are no translations for this edition of VirtualBox, but only for the official one. We could perhaps use their packages to translate VirtualBox, or we could wait for them to implement the translations. But now it is only available in English.

Don't ask me for translations. Thanks in advance.

**Comment by ivan-hc** [comment]
@newyorkthink I must let you know that, as expected, extension pack does not work, also if I've implemented it into an experimental build.

I've done the following test. To the file [create-arch-bootstrap.sh](https://github.com/ivan-hc/VirtualBox-appimage/blob/main/create-arch-bootstrap.sh) I added this step, into another repository I use:
```
# Add extension pack
wget https://download.virtualbox.org/virtualbox/"${vboxver}"/Oracle_VM_VirtualBox_Extension_Pack-"${vboxver}".vbox-extpack -O ./Extension_Pack.tar
mkdir -p shrunk
tar xfC ./Extension_Pack.tar shrunk
rm -r shrunk/{darwin*,solaris*,win*}
tar -c --gzip --file shrunk.vbox-extpack -C shrunk .
install -Dm 644 shrunk.vbox-extpack \
	"${bootstrap}"/usr/share/virtualbox/extensions/Oracle_VM_VirtualBox_Extension_Pack-"${vboxver}".vbox-extpack
install -Dm 644 shrunk/ExtPack-license.txt \
	"${bootstrap}"/usr/share/licenses/virtualbox-ext-oracle/PUEL
```
this have integrated the extension pack (I've followed the instructions [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=virtualbox-ext-oracle))

![Istantanea_2024-07-29_05-32-21](https://github.com/user-attachments/assets/d0870502-6094-47e3-b7ac-d46b94f6237e)
![Istantanea_2024-07-29_05-32-34](https://github.com/user-attachments/assets/ae4c6708-d1da-4b3f-82a1-98229516a311)

as you can see, the files in this experimental build are in place.

For now, you can download it from [here](https://github.com/ivan-hc/Conty/releases/tag/continuous-virtualbox) as a simple conty.sh file or use [this script](https://github.com/ivan-hc/VirtualBox-appimage/blob/main/virtualbox-conty-builder.sh) to convert it to an AppImage, as workflow of this repository already do (the script creates the AppDir and downloads that artifact into it, and then converts the AppDir into an AppImage).

However, still USB support is not enabled. I mounted an external HDD on the host, but thill I can't select it from the virual machine

![Istantanea_2024-07-29_05-38-02](https://github.com/user-attachments/assets/fc773a9d-1bb4-472f-a271-62d20dd99129)

I also added my user to the "vboxusers" group
```
sudo groupadd -r vboxusers -U ivan
```
and still there is nothing to do.

I tell you this not to sound too rude. I know that the features you want are useful, I would like them too. After all, VirtualBox is one of my favorite apps, and so this is my favorite AppImage.

However, let's face it: this app cannot be completely disconnected from the host system kernel, there is still a long way to go.

I suggest you take a look at another AppImage I created, GNOME Boxes, at https://github.com/ivan-hc/Boxes-appimage

But even there you need to install some APT packages, since you are on Kali linux, here they are:
```
libvirt-daemon-driver-qemu
libvirt-daemon-system
```
they will not make GNOME Boxes 100% functional anyway (because of the 3D acceleration), but maybe you might like that Appimage more than this one.

See you next.
